FROM mayanedms/mayanedms:3

ENV PORT=5000

EXPOSE ${PORT}
# EXPOSE ${PORT}
# ENTRYPOINT [ "executable", "--port", $PORT ]
# USER root
COPY ./scripts/run_frontend.sh /usr/local/bin/run_frontend.sh
COPY ./scripts/mayan.conf /etc/supervisor/conf.d/mayan.conf

RUN chmod +x /usr/local/bin/run_frontend.sh

# USER mayan

# CMD [ "su mayan", "-c", "/opt/mayan-edms/bin/gunicorn -w 2 mayan.wsgi --max-requests 500 --max-requests-jitter 50 --worker-class sync --bind 0.0.0.0:5000 --timeout 120" ]

# EXPOSE 8000

# CMD ["run_all"]

# ENV PYTHONBUFFERED=1
